  name: 'Update-tf-var'
  description: Updates a json tfvar
  inputs:
    file_name:
      type: string
      required: true
    field:
      type: string
      required: true
    value:
      type: string
      required: true

  runs:
    using: composite
    steps:
      - name: checkout
        id: checkout_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          branch: 'release-notes'
      -  name: Update json-values description
         uses: jossef/action-set-json-field@v2.1
         with:
           file: "${{ inputs.file_name }}"
           field: "${{ inputs.field}}"
           value: "${{ inputs.value }}"
