  name: 'Update-tf-var'
  description: Updates a json tfvar
  inputs:
    file_name:
      type: string
      required: true
    field:
      type: string
      required: true
    value:
      type: string
      required: true
    token:
      type: string
      required: true
  runs:
    using: composite
    steps:
      - name: create_branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
        with:
          branch: update_json_${{ inputs.field }}_${{ inputs.value }}
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: update_json_${{ inputs.field }}_${{ inputs.value }}
      - name: Update json-values description
        uses: jossef/action-set-json-field@v2.1
        with:
           file: "${{ inputs.file_name }}"
           field: "${{ inputs.field}}"
           value: "${{ inputs.value }}"
      - name: Commit files
        shell: bash
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add -A
         git commit -m "updating ${{ inputs.field }} with ${{ inputs_value }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
         github_token: ${{ inputs.token }}
         branch: update_json_${{ inputs.field }}_${{ inputs.value }}
