name: TRE Deploy Generated Schema
on:
  workflow_dispatch:
env:
  RUN_NUMBER: ${{ github.run_id }}${{ github.run_attempt }}
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
#           git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - run: |
          ./.github/scripts/setup.sh
           git config --global user.email ian.hoyle@nationalarchives.gov.uk
           git config --global user.name 'Ian Hoyle'
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
          touch hello.txt
          git commit -m -S "hello"
      - name: Create Pull Request
        run: gh pr create --fill --label 'Version bump'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
