name: TRE Deploy Generated Schema
on:
  workflow_dispatch:
env:
  RUN_NUMBER: ${{ github.run_id }}${{ github.run_attempt }}
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - run: |
          git config --global user.email "${{ steps.import-gpg.outputs.email }}"
          git config --global user.name "${{ steps.import-gpg.outputs.name }}"
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
      - run: |
          touch hello.txt
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Create Pull Request
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/nationalarchives/da-transform-schemas/pulls \
          -f title='Version bump' \
          -f body='Please pull this version bump!' \
          -f head='$BRANCH_NAME' \
          -f base='main'
         

