
name: Court Document Parser CI/CD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Check version
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks latest tag in repository
      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ../terraform/staging.tfvars
          field: vb_version
          value: "hello" 
