
name: Court Document Parser CI/CD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  add:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: add_me
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks latest tag in repository
      - name: add
        shell: bash
        run: |
          add=$(( 3 + 2 ))
          echo $add
  multiply:        
    runs-on: ubuntu-latest
    name: multiply
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks latest tag in repository
      - name: mult
        shell: bash
        run: |
          mu=$(( 3 * 2 ))
          echo $mu
  divide:        
    runs-on: ubuntu-latest
    name: divide
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks latest tag in repository
      - name: div
        shell: bash
        run: |
          di=$(( 3 / 0 ))
          echo $di   
          exit 1
  end:
     runs-on: ubuntu-latest
     needs: [add, multiply, divide]
     if:  ${{success()}}
     steps:
        - name: div
          shell: bash
          run: echo "SUCCESS"
     
     
  
